package com.stefanini.model;
// Generated 07/11/2016 12:04:56 by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Categoria generated by hbm2java
 */
@Entity
@Table(name = "categoria")
public class Categoria implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy = IDENTITY)
	private Integer idCategoria;
	
	@Column(name = "descricaoCategoria", length = 50)
	private String descricaoCategoria;

	public Categoria() {
	}

	public Categoria(String descricaiCategoria) {
		this.descricaoCategoria = descricaiCategoria;
	}

	
	public Integer getIdCategoria() {
		return this.idCategoria;
	}

	public void setIdCategoria(Integer idCategoria) {
		this.idCategoria = idCategoria;
	}


	public String getDescricaiCategoria() {
		return this.descricaoCategoria;
	}

	public void setDescricaiCategoria(String descricaiCategoria) {
		this.descricaoCategoria = descricaiCategoria;
	}

}
