package com.stefanini.model;
// Generated 07/11/2016 12:04:56 by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Infracoes generated by hbm2java
 */
@Entity
@Table(name = "infracoes")
public class Infracoes implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idInfracao", unique = true, nullable = false)
	private Integer idInfracao;

	@ManyToOne
	@JoinColumn(name = "idAgente")
	private Agente agente;

	@ManyToOne
	@JoinColumn(name = "idLocalInfracao")
	private Localinfracao localInfracao;

	@ManyToOne
	@JoinColumn(name = "idTipoInfracao")
	private Tipoinfracao tipoInfracao;

	@ManyToOne
	@JoinColumn(name = "placa")
	private Veiculos placaVeic;

	private Integer velocidade;

	public Infracoes() {
	}

	public Infracoes(Agente idAgente, Localinfracao idLocalInfracao, Tipoinfracao idTipoInfracao, Veiculos placa) {
		this.agente = idAgente;
		this.localInfracao = idLocalInfracao;
		this.tipoInfracao = idTipoInfracao;
		this.placaVeic = placa;
	}

	public Integer getIdInfracao() {
		return idInfracao;
	}

	public void setIdInfracao(Integer idInfracao) {
		this.idInfracao = idInfracao;
	}

	public Agente getAgente() {
		return agente;
	}

	public void setAgente(Agente agente) {
		this.agente = agente;
	}

	public Localinfracao getLocalInfracao() {
		return localInfracao;
	}

	public void setLocalInfracao(Localinfracao localInfracao) {
		this.localInfracao = localInfracao;
	}

	public Tipoinfracao getTipoInfracao() {
		return tipoInfracao;
	}

	public void setTipoInfracao(Tipoinfracao tipoInfracao) {
		this.tipoInfracao = tipoInfracao;
	}

	public Veiculos getPlacaVeic() {
		return placaVeic;
	}

	public void setPlacaVeic(Veiculos placaVeic) {
		this.placaVeic = placaVeic;
	}

	public Integer getVelocidade() {
		return velocidade;
	}

	public void setVelocidade(Integer velocidade) {
		this.velocidade = velocidade;
	}

}
