package com.stefanini.model;
// Generated 07/11/2016 12:04:56 by Hibernate Tools 4.3.1.Final

import java.io.Serializable;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Telefones generated by hbm2java
 */
@Entity
@Table(name = "telefones", catalog = "hackaton")
public class Telefones implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "numero", column = @Column(name = "numero", nullable = true)),
			@AttributeOverride(name = "ddd", column = @Column(name = "ddd", nullable = true)),
			@AttributeOverride(name = "cpfProprietario", column = @Column(name = "cpfProprietario", nullable = true)) })
	private TelefonesId id;

	@ManyToOne
	@JoinColumn(name = "TIPO_ID")
	private Tipotelefone tipotelefone;

	public Telefones() {
	}

	public Telefones(TelefonesId id, Tipotelefone idTipoTelefone) {
		this.id = id;
		this.tipotelefone = idTipoTelefone;
	}

	public TelefonesId getId() {
		return id;
	}

	public void setId(TelefonesId id) {
		this.id = id;
	}

	public Tipotelefone getTipotelefone() {
		return tipotelefone;
	}

	public void setTipotelefone(Tipotelefone tipotelefone) {
		this.tipotelefone = tipotelefone;
	}

}
