package com.stefanini.model;
// Generated 07/11/2016 12:04:56 by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tipoinfracao generated by hbm2java
 */
@Entity
@Table(name = "tipoinfracao")
public class Tipoinfracao implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idTipoInfracao", unique = true, nullable = false)
	private Integer idTipoInfracao;
	
	@Column(name = "descricaoTipoInfracao", length = 50)
	private String descricaoTipoInfracao;
	
	@Column(name = "valor", precision = 22, scale = 0)
	private Double valor;

	public Tipoinfracao() {
	}

	public Tipoinfracao(String descricaoTipoInfracao, Double valor) {
		this.descricaoTipoInfracao = descricaoTipoInfracao;
		this.valor = valor;
	}

	
	public Integer getIdTipoInfracao() {
		return this.idTipoInfracao;
	}

	public void setIdTipoInfracao(Integer idTipoInfracao) {
		this.idTipoInfracao = idTipoInfracao;
	}

	
	public String getDescricaoTipoInfracao() {
		return this.descricaoTipoInfracao;
	}

	public void setDescricaoTipoInfracao(String descricaoTipoInfracao) {
		this.descricaoTipoInfracao = descricaoTipoInfracao;
	}


	public Double getValor() {
		return this.valor;
	}

	public void setValor(Double valor) {
		this.valor = valor;
	}

}
